force-app/main/default/objects/DE_ResourceLink__c/DE_ResourceLink__c.object-meta.xml
<CustomObject>
    <label>Generic Highlight</label>
    <nameField>
        <displayFormat>RL-{0000}</displayFormat>
        <label>Resource ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Generic Highlights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DE_ResourceLink__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Trailhead</fullName>
            </value>
            <value>
                <fullName>Quick Links</fullName>
            </value>
            <value>
                <fullName>Similar Opps</fullName>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>Offers</fullName>
            </value>
            <value>
                <fullName>Reports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DE_ResourceLink__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>2nd line below the title</description>
    <inlineHelpText>2nd line below the title</inlineHelpText>
    <label>Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DE_ResourceLink__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <label>Icon</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/DE_ResourceLink__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <label>Navigation Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/DE_ResourcesDemo.cls
public with sharing class DE_ResourcesDemo {
    @AuraEnabled(cacheable=true)
    public static list<DE_ResourceLink__c> getResources(string category){
        try {
            return [select Id,Name,Link__c,Label__c,Icon__c,Image_URL__c,Date__c,Description__c from DE_ResourceLink__c where Category__c=:category];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
}